version: 2.1

jobs:
  node-test:
    machine: true
    steps:
      - checkout
      - run:
        command: |
          sudo apt install python
          nvm install v8.11.3

workflows:
  node-tests:
    jobs:
      - node-test