version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  setup:
    machine: true
    steps:
      - run:
        command: |
          sudo apt install python
workflows:
  node-tests:
    jobs:
      - setup
      - node/test