#!/bin/sh

current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

if [ 'master' = ${current_branch} ]
then
  echo "ERROR: Cannot push to master. Switch to a different branch and create a pull request."
  exit 1 # push will not execute
fi


CMD="npm run prepush"

#run the prepush command and check the result
$CMD
RESULT=$?
if [ $RESULT -ne 0 ]; then 
	echo "failed $CMD"
	exit 1
fi

exit 0
